---
- name: Create /etc/goss directory
  file:
    state: directory
    dest: /etc/goss
    owner: root
    group: root
    mode: '0775'

- name: Generate /etc/goss/vars.yaml file
  template:
    src: vars.yaml.j2
    dest: /etc/goss/vars.yaml
    owner: root
    group: root
    mode: '0664'

- name: Download goss
  ansible.builtin.get_url:
    url: "https://github.com/goss-org/goss/releases/download/{{ goss_version }}/goss-linux-amd64"
    dest: "/usr/local/bin/goss"
    owner: root
    group: root
    mode: '0775'

- name: Deploy goss and gossfiles
  copy:
    src: "{{ item }}"
    dest: "/etc/goss/{{ item }}"
    owner: root
    group: root
    mode: '0664'
  loop:
    - domain.yaml
    - goss.yaml
    - grub.yaml
    - network.yaml
    - packages.yaml
    - pending-reboot.yaml
    - services.yaml
    - sshd.yaml
    - systemd.yaml
    - template-debian.yaml
